sudo: required
services:
  - docker

before_install:
  - docker build -t tsosen/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tsosen/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-930189314126"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
